### ISSUE TITLE
Cannot run DIN collective dynamic

### ISSUE THREAD

**Issue by Nicolas99-9** [JacobYuan7/DIN-Group-Activity-Recognition-Benchmark#18]
Hello @JacobYuan7 

I could train the first stage of the collective model.
However, I ran into an error when running the stage 2 (collective model).
(I did not edit the config files)

Traceback (most recent call last):
 ```
 File "/home/nicolas/other/DIN-Group-Activity-Recognition-Benchmark/scripts/train_collective_stage2_dynamic.py", line 58, in <module>
    train_net(cfg)
  File "/home/nicolas/other/DIN-Group-Activity-Recognition-Benchmark/./train_net_dynamic.py", line 124, in train_net
    train_info=train(training_loader, model, device, optimizer, epoch, cfg)
  File "/home/nicolas/other/DIN-Group-Activity-Recognition-Benchmark/./train_net_dynamic.py", line 333, in train_collective
    activities_scores = model((batch_data[0], batch_data[1], batch_data[4]))
  File "/opt/conda/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/nicolas/other/DIN-Group-Activity-Recognition-Benchmark/./infer_model.py", line 1297, in forward
    boxes_states = graph_boxes_features + boxes_features  # 1, T, N, NFG
TypeError: can only concatenate tuple (not "Tensor") to tuple
```

**Comment by JacobYuan7** [comment]
I need more information to cope with this issue. I haven't encountered this problem. Can you provide more?

**Comment by JacobYuan7** [comment]
I closed this issue since there is no update. Feel free to re-open it.
